### ISSUE TITLE
Create a Ruby gem

### ISSUE THREAD

**Issue by JohnRiv** [Comcast/Surf-N-Perf#3]
Create a surfnperf Ruby Gem that includes the minified source in the vendor directory and allows easy access to the code for the <HEAD> of the document specificed in the README via a partial that Rails or Middleman can use.

**Comment by mdb** [comment]
Do you think releasing Surf-N-Perf as a bower component and then allowing Ruby/Rails/Middleman projects to require the bower component via rails-assets could be a preferred alternative path towards this need?

If so, this would save Surf-N-Perf from having to manage a Ruby build process on top of a JS build process.

**Comment by JohnRiv** [comment]
Pull Request #34 made this possible. Gem is now published: https://rubygems.org/gems/surfnperf
