### ISSUE TITLE
Switch from gh-pages to /docs folder for documentation

### ISSUE THREAD

**Issue by JohnRiv** [Comcast/Surf-N-Perf#53]
See https://github.com/blog/2233-publish-your-project-documentation-with-github-pages for details on the new GitHub feature. This should simplify things regarding out documentation build process.

**Comment by rottina** [comment]
@johnriv were you thinking of keeping jsdoc auto-generation or just migrate it and have the docs live statically in the /docs folder?

**Comment by JohnRiv** [comment]
I'd still like the JS Doc auto-generation

**Comment by JohnRiv** [comment]
Now that we're using Github Actions (https://github.com/Comcast/Surf-N-Perf/pull/101), I think the builds are in a good spot. Don't need this anymore.
