### ISSUE TITLE
add getFirstContentfulPaint()

### ISSUE THREAD

**Issue by JohnRiv** [Comcast/Surf-N-Perf#80]
should behave similar to getFirstPaint() with the `"first-contentful-paint"` name instead of `"first-paint"`

See https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming for docs

**Comment by mkamranhamid** [comment]
In `surfnperf.js` file whenever `getFirstPaint` function is called you want to lookup for `first-contentful-paint` rather `first-paint`(which is a current behaviour), right?

**Comment by JohnRiv** [comment]
closed via #85
